development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  encoding: utf8
  database: cameo
  pool: 5
  username: wangzc
  password: wzc
  socket: /tmp/mysql.sock
  timeout: 5000
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: cameo
  pool: 5
  username: wangzc
  password: wzc
  socket: /tmp/mysql.sock
  timeout: 5000
  host: localhost
