development:
  adapter: mysql2
  encoding: utf8
  database: cameo
  pool: 5
  username: root
  password: wzc
  socket: /var/run/mysqld/mysqld.sock
  timeout: 5000
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: cameo
  pool: 5
  username: wangzc
  password: wzc
  socket: /tmp/mysql.sock
  timeout: 5000
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: cameo
  pool: 5
  username: wangzc
  password: wzc
  socket: /tmp/mysql.sock
  timeout: 5000
  host: localhost
